/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cdhmed.view;

import cdhmed.controller.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author batista
 */
public class FrameMedico extends javax.swing.JFrame {

    /**
     * Creates new form Medico
     */
    public FrameMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jButtonNovoMed = new javax.swing.JButton();
        jButtonAlterarMed = new javax.swing.JButton();
        jButtonExcluirMed = new javax.swing.JButton();
        jButtonListarMed = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldCRM = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelCRM = new javax.swing.JLabel();
        jTextFieldCPF1 = new javax.swing.JTextField();
        jButtonGravarCAD = new javax.swing.JButton();
        jButtonCancelarCAD = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();

        jDesktopPane2.setBackground(new java.awt.Color(238, 238, 238));
        jDesktopPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(111, 111, 111));
        jLabel3.setText("ALTERAR");

        jDesktopPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel3)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MÉDICO");

        jButtonNovoMed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonNovoMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cdhmed/etc/Add.png"))); // NOI18N
        jButtonNovoMed.setText("Novo");
        jButtonNovoMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoMedActionPerformed(evt);
            }
        });

        jButtonAlterarMed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAlterarMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cdhmed/etc/Edit.png"))); // NOI18N
        jButtonAlterarMed.setText("Alterar");
        jButtonAlterarMed.setPreferredSize(new java.awt.Dimension(139, 42));
        jButtonAlterarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarMedActionPerformed(evt);
            }
        });

        jButtonExcluirMed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonExcluirMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cdhmed/etc/Excluir.png"))); // NOI18N
        jButtonExcluirMed.setText("Excluir");
        jButtonExcluirMed.setPreferredSize(new java.awt.Dimension(139, 42));
        jButtonExcluirMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirMedActionPerformed(evt);
            }
        });

        jButtonListarMed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonListarMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cdhmed/etc/Lupa.png"))); // NOI18N
        jButtonListarMed.setText("Listar");
        jButtonListarMed.setPreferredSize(new java.awt.Dimension(139, 42));
        jButtonListarMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonListarMedMousePressed(evt);
            }
        });
        jButtonListarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarMedActionPerformed(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(238, 238, 238));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelNome.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelNome.setText("Informe o nome do médico:");

        jLabelCPF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelCPF.setText("Informe o CPF:");

        jLabelCRM.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelCRM.setText("Informe o CRM:");

        jButtonGravarCAD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonGravarCAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cdhmed/etc/Gravar 32x32.png"))); // NOI18N
        jButtonGravarCAD.setText("Gravar");
        jButtonGravarCAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarCADActionPerformed(evt);
            }
        });

        jButtonCancelarCAD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCancelarCAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cdhmed/etc/Cancelar.png"))); // NOI18N
        jButtonCancelarCAD.setText("Cancelar");
        jButtonCancelarCAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCADActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(111, 111, 111));
        jLabelTitle.setText("CADASTRO");

        jDesktopPane1.setLayer(jLabelNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldCRM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelCRM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldCPF1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonGravarCAD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCancelarCAD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jTextFieldCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldCRM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCRM, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabelCPF)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(jButtonGravarCAD, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonCancelarCAD, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(256, 256, 256))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCRM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGravarCAD)
                    .addComponent(jButtonCancelarCAD))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNovoMed, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterarMed, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonExcluirMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonListarMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovoMed)
                    .addComponent(jButtonAlterarMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListarMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirMedActionPerformed
        jLabelTitle.setText("EXCLUIR");
        jLabelCPF.setVisible(false);
        jLabelCRM.setVisible(false);
        jLabelNome.setVisible(false);
        jTextFieldCPF1.setText("");
        jTextFieldCPF1.setVisible(false);
        jTextFieldCRM.setText("");
        jTextFieldCRM.setVisible(false);
        jTextFieldNome.setText("");
        jTextFieldNome.setVisible(false);
        jButtonGravarCAD.setVisible(false);
        jButtonCancelarCAD.setVisible(false);
    }//GEN-LAST:event_jButtonExcluirMedActionPerformed

    private void jButtonListarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarMedActionPerformed
        jLabelTitle.setText("LISTAR");
        jLabelCPF.setVisible(false);
        jLabelCRM.setVisible(false);
        jLabelNome.setVisible(false);
        jTextFieldCPF1.setText("");
        jTextFieldCPF1.setVisible(false);
        jTextFieldCRM.setText("");
        jTextFieldCRM.setVisible(false);
        jTextFieldNome.setText("");
        jTextFieldNome.setVisible(false);
        jButtonGravarCAD.setVisible(false);
        jButtonCancelarCAD.setVisible(false);
    }//GEN-LAST:event_jButtonListarMedActionPerformed

    private void jButtonListarMedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonListarMedMousePressed

    }//GEN-LAST:event_jButtonListarMedMousePressed

    private void jButtonGravarCADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarCADActionPerformed
        if(jTextFieldNome.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Informe o Nome", "Campo em branco", 0);
        }else{
        Controller.addMedico(jTextFieldNome.getText(), jTextFieldCPF1.getText(), jTextFieldCRM.getText());
        jTextFieldNome.setText("");
        jTextFieldCPF1.setText("");
        jTextFieldCRM.setText("");
        }
    }//GEN-LAST:event_jButtonGravarCADActionPerformed

    private void jButtonCancelarCADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCADActionPerformed
        jTextFieldCRM.setText("");
        jTextFieldCPF1.setText("");
        jTextFieldNome.setText("");
    }//GEN-LAST:event_jButtonCancelarCADActionPerformed

    private void jButtonNovoMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoMedActionPerformed
        jLabelTitle.setText("CADASTRAR");
        jLabelCPF.setVisible(true);
        jLabelCRM.setVisible(true);
        jLabelNome.setVisible(true);
        jTextFieldCPF1.setText("");
        jTextFieldCPF1.setVisible(true);
        jTextFieldCRM.setText("");
        jTextFieldCRM.setVisible(true);
        jTextFieldNome.setText("");
        jTextFieldNome.setVisible(true);
        jButtonGravarCAD.setVisible(true);
        jButtonCancelarCAD.setVisible(true);
    }//GEN-LAST:event_jButtonNovoMedActionPerformed

    private void jButtonAlterarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarMedActionPerformed
        jLabelTitle.setText("ALTERAR");
        jLabelCPF.setVisible(false);
        jLabelCRM.setVisible(false);
        jLabelNome.setVisible(false);
        jTextFieldCPF1.setText("");
        jTextFieldCPF1.setVisible(false);
        jTextFieldCRM.setText("");
        jTextFieldCRM.setVisible(false);
        jTextFieldNome.setText("");
        jTextFieldNome.setVisible(false);
        jButtonGravarCAD.setVisible(false);
        jButtonCancelarCAD.setVisible(false);
    }//GEN-LAST:event_jButtonAlterarMedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarMed;
    private javax.swing.JButton jButtonCancelarCAD;
    private javax.swing.JButton jButtonExcluirMed;
    private javax.swing.JButton jButtonGravarCAD;
    private javax.swing.JButton jButtonListarMed;
    private javax.swing.JButton jButtonNovoMed;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCRM;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextFieldCPF1;
    private javax.swing.JTextField jTextFieldCRM;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
