/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cdhmed.view;

import cdhmed.controller.Controller;
import cdhmed.model.Medico;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author batista
 */
public class FrameMedico extends javax.swing.JFrame {

    /**
     * Creates new form Listar
     */
    public FrameMedico() {
        initComponents();
        inserirPesquisaMedico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonNovoMed = new javax.swing.JButton();
        jButtonAlterarMed = new javax.swing.JButton();
        jButtonExcluirMed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cdhmed/etc/Lupa.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "CRM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(140);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
        }

        jLabel1.setText("Informe o nome:");

        jButtonNovoMed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonNovoMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cdhmed/etc/Add.png"))); // NOI18N
        jButtonNovoMed.setText("Novo");
        jButtonNovoMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoMedActionPerformed(evt);
            }
        });

        jButtonAlterarMed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAlterarMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cdhmed/etc/Edit.png"))); // NOI18N
        jButtonAlterarMed.setText("Alterar");
        jButtonAlterarMed.setPreferredSize(new java.awt.Dimension(139, 42));
        jButtonAlterarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarMedActionPerformed(evt);
            }
        });

        jButtonExcluirMed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonExcluirMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cdhmed/etc/Excluir.png"))); // NOI18N
        jButtonExcluirMed.setText("Excluir");
        jButtonExcluirMed.setPreferredSize(new java.awt.Dimension(139, 42));
        jButtonExcluirMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirMedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNovoMed, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAlterarMed, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonExcluirMed, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovoMed)
                    .addComponent(jButtonAlterarMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) jTable1.getModel();
        tabela.setNumRows(0);
        inserirPesquisaMedico();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonNovoMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoMedActionPerformed
        FrameCadMedico cadMedico =  new FrameCadMedico();
        cadMedico.setVisible(true);
    }//GEN-LAST:event_jButtonNovoMedActionPerformed

    private void jButtonAlterarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarMedActionPerformed
      FrameAltMedico frameAlterar = new FrameAltMedico();
      frameAlterar.insereDadosCamposdeTexto((int) jTable1.getValueAt(jTable1.getSelectedRow(),0));
      frameAlterar.setVisible(true);
    }//GEN-LAST:event_jButtonAlterarMedActionPerformed

    private void jButtonExcluirMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirMedActionPerformed
        Controller.excluirMed((int) jTable1.getValueAt(jTable1.getSelectedRow(),0));
        inserirPesquisaMedico();
    }//GEN-LAST:event_jButtonExcluirMedActionPerformed

    public void inserirPesquisaMedico() {
        setLocationRelativeTo(null);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("Código");//Colocar o titulo da coluna
        jTable1.getColumnModel().getColumn(1).setHeaderValue("Nome");//Colocar o titulo da coluna
        jTable1.getColumnModel().getColumn(2).setHeaderValue("CPF");//Colocar o titulo da coluna
        jTable1.getColumnModel().getColumn(2).setHeaderValue("CRM");//Colocar o titulo da coluna
      
        jTable1.setCellSelectionEnabled(false);
        jTable1.setRowSelectionAllowed(true);

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        ArrayList<Medico> listaMedico = Controller.pesquisaMed(jTextField1.getText().toUpperCase());
        if (!listaMedico.isEmpty()) {
            Object[] fila = new Object[model.getColumnCount()];
            for (int i = 0; i < listaMedico.size(); i++) {
                fila[0] = listaMedico.get(i).getIdMedico();
                fila[1] = listaMedico.get(i).getNome();
                fila[2] = listaMedico.get(i).getCpf();
                fila[3] = listaMedico.get(i).getCrm();
                model.addRow(fila);
            }
        }else JOptionPane.showMessageDialog(null, "Nenhum cadastro encontrado", "Cadastro vazio", 0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAlterarMed;
    private javax.swing.JButton jButtonExcluirMed;
    private javax.swing.JButton jButtonNovoMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
