/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cdhmed.view;

/**
 *
 * @author batista
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNovoMed = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuAlterarMed = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuExcluirMed = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuListarMed = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuNovoRecibo = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuAlterarRecibo = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuExcluirRecibo = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuListarRecibo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRINCIPAL");

        jMenuBar1.setPreferredSize(new java.awt.Dimension(126, 30));

        jMenuNovoMed.setText("Médico");

        jMenuItem1.setText("Novo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuNovoMed.add(jMenuItem1);
        jMenuNovoMed.add(jSeparator1);

        jMenuAlterarMed.setText("Alterar");
        jMenuAlterarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlterarMedActionPerformed(evt);
            }
        });
        jMenuNovoMed.add(jMenuAlterarMed);
        jMenuNovoMed.add(jSeparator2);

        jMenuExcluirMed.setText("Excluir");
        jMenuNovoMed.add(jMenuExcluirMed);
        jMenuNovoMed.add(jSeparator3);

        jMenuListarMed.setText("Listar");
        jMenuNovoMed.add(jMenuListarMed);

        jMenuBar1.add(jMenuNovoMed);

        jMenu2.setText("Recibo");

        jMenuNovoRecibo.setText("Novo");
        jMenuNovoRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovoReciboActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuNovoRecibo);
        jMenu2.add(jSeparator4);

        jMenuAlterarRecibo.setText("Alterar");
        jMenuAlterarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlterarReciboActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuAlterarRecibo);
        jMenu2.add(jSeparator5);

        jMenuExcluirRecibo.setText("Excluir");
        jMenu2.add(jMenuExcluirRecibo);
        jMenu2.add(jSeparator6);

        jMenuListarRecibo.setText("Listar");
        jMenu2.add(jMenuListarRecibo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sair");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       Medico FrameMedico = new Medico();
       FrameMedico.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuAlterarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlterarMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAlterarMedActionPerformed

    private void jMenuNovoReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovoReciboActionPerformed
        Recibo FrameRecibo = new Recibo();
        FrameRecibo.setVisible(true);
    }//GEN-LAST:event_jMenuNovoReciboActionPerformed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
        System.exit(0);
    }//GEN-LAST:event_jMenu3MousePressed

    private void jMenuAlterarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlterarReciboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAlterarReciboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuAlterarMed;
    private javax.swing.JMenuItem jMenuAlterarRecibo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExcluirMed;
    private javax.swing.JMenuItem jMenuExcluirRecibo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuListarMed;
    private javax.swing.JMenuItem jMenuListarRecibo;
    private javax.swing.JMenu jMenuNovoMed;
    private javax.swing.JMenuItem jMenuNovoRecibo;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
